### ISSUE TITLE
Never worked for me

### ISSUE THREAD

**Issue by melisay** [thenbrent/paypal-digital-goods#37]
http://paypal.brentshepherd.com/

There is an error on the main example. Will this ever be fixed? 

SetExpressCheckout failed: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure(35)

**Comment by thenbrent** [comment]
Thanks for letting me know. That issue is caused by my demo server's OpenSSL version being out-of-date combined with updates to PayPal's requirements on SSL certificates. This has more details: https://devblog.paypal.com/paypal-ssl-certificate-changes/

I will try to get it fixed up sometime in the next week or two. But it's really a server issue not a library issue, the library will work fine so until I get the server fixed up, you can still use the [examples](https://github.com/thenbrent/paypal-digital-goods-php-examples/) on your own server/development environment with compatible SSL.

**Comment by blueminded** [comment]
Hi, there.

I'm in the same trouble. I'm using MAMP Free and I used to test digital payments with this library but recently this error came up. Do you know how to solve it I understand that is something in Apache and ssl config but I'm kind of lost. Any help would be appreciated. Thanks.

**Comment by thenbrent** [comment]
@blueminded I had to fix it with MAMP a few weeks ago. Following this guide helped me get it fixed locally: http://stackoverflow.com/questions/32431465/mamp-ssl-error-error14077410ssl-routinesssl23-get-server-hellosslv3-alert/32431466#32431466
