### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by NitinPrakash** [thenbrent/paypal-digital-goods#40]
If it can be done via paypal-configuration-class.php then this class can be more useful for developers.
Thanks in advance

$api_request  .= '&L_PAYMENTREQUEST_0_ITEMCATEGORY'.$item_count.'=**Digital**'

or

$api_request  .= '&L_PAYMENTREQUEST_0_ITEMCATEGORY'.$item_count.'=**Physical**'

**Comment by thenbrent** [comment]
@NitinPrakash this library was written strictly for the PayPal Digital Goods API, which _required_ the item category to always be `Digital`, that's why it's not configurable.

The Digital Goods API is no longer supported for new merchants, and it does share _a lot_ of similarities with the PayPal Express Checkout API, where `Physical` items are supported, so in theory, this library could be ported or refactored to be a generic Express Checkout library.

However, I've personally lost way too much of my life the last 5 years working with assorted PayPal APIs and have no intention of losing any more by modifying this library to be a generic Express Checkout library (which has other requirements). If you want to make it into that, you could fork it use it as a base (it's 100% GPL licensed).

**Comment by NitinPrakash** [comment]
@thenbrent Thanks brother.

**Comment by GaganTiwari** [comment]
Ya exactly @NitinPrakash it can be done via paypal-configuration-class.php then this class can be more useful for developers.

Thanks in advance both of u @NitinPrakash and @thenbrent .
